application: onephotoblogger
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
- url: /admin
  script: _go_app
- url: /login
  script: _go_app
- url: /upload_page
  script: _go_app
